services:
  barracuda-jetson:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-jetson
    container_name: barracuda-jetson
    tty: true
    network_mode: host
    ipc: host
    ports:
      - 8766:8765
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  barracuda-jetson-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-jetson-dev
    container_name: barracuda-jetson-dev
    tty: true
    network_mode: host
    ipc: host
    ports:
      - 8765:8765
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../src:/ros2_ws/src
    profiles: ["dev"]
